name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd lab9
          npm install

      - name: Build app
        run: |
          cd lab9
          npm run build

      - name: Run Cypress Tests
        run: |
          cd lab9
          npm start &    # start server in background
          npx wait-on http://localhost:3000
          npx cypress run
