name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: lab9

      - name: Build app
        run: npm run build
        working-directory: lab9

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
          project: lab9
